{% set name = "pytest-dependency" %}
{% set version = "0.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 934b0e6a39d95995062c193f7eaeed8a8ffa06ff1bcef4b62b0dc74a708bacc1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4.0
    - setuptools_scm
  run:
    - pytest >=3.7.0
    - python >=3.4.0

test:
  imports:
    - pytest_dependency
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/RKrahl/pytest-dependency
  summary: Manage dependencies of tests
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Windiana42
